#include "token_type.h"
#include <string.h>

hashmap_t token_hashmap;

void init_kw_hashmap()
{
	kvpair_t pairs[] = 
	{
		{ "li", LI },
		{ "add", ADD },
		{ "lb", LB },
		{ "beqz", BEQZ },
		{ "addi", ADDI },
		{ "j", J },
		{ "mv", MV },
		{ "ret", RET },
		{ "sb", SB },
		{ "bge", BGE },
		{ "sd", SD },
		{ "call", CALL },
		{ "srai", SRAI },
		{ "sub", SUB },
		{ "ld", LD },
		{ "slli", SLLI },
		{ "lw", LW },
		{ "ble", BLE },
		{ "bnez", BNEZ },
		{ "fld", FLD },
		{ "fsw", FSW },
		{ "la", LA },
		{ "bgt", BGT },
		{ "flw", FLW },
		{ "fadd.s", FADDS },
		{ "fmul.s", FMULS },
		{ "fmv.s", FMVS },
		{ "fmv.s.x", FMVSX },
		{ "flt.s", FLTS },
		{ "fgt.s", FGTS },
		{ "fsqrt.d", FSQRTD },
		{ "fadd.d", FADDD },
		{ "fmul.d", FMULD },
		{ "fsub.d", FSUBD },
		{ "zero", ZERO },
		{ "ra", RA },
		{ "sp", SP },
		{ "gp", GP },
		{ "tp", TP },
		{ "t0", T0 },
		{ "t1", T1 },
		{ "t2", T2 },
		{ "s0", S0 },
		{ "fp", FP },
		{ "s1", S1 },
		{ "a0", A0 },
		{ "a1", A1 },
		{ "a2", A2 },
		{ "a3", A3 },
		{ "a4", A4 },
		{ "a5", A5 },
		{ "a6", A6 },
		{ "a7", A7 },
		{ "s2", S2 },
		{ "s3", S3 },
		{ "s4", S4 },
		{ "s5", S5 },
		{ "s6", S6 },
		{ "s7", S7 },
		{ "s8", S8 },
		{ "s9", S9 },
		{ "s10", S10 },
		{ "s11", S11 },
		{ "t3", T3 },
		{ "t4", T4 },
		{ "t5", T5 },
		{ "t6", T6 },
		{ "ft0", FT0 },
		{ "ft1", FT1 },
		{ "ft2", FT2 },
		{ "ft3", FT3 },
		{ "ft4", FT4 },
		{ "ft5", FT5 },
		{ "ft6", FT6 },
		{ "ft7", FT7 },
		{ "fs0", FS0 },
		{ "fs1", FS1 },
		{ "fa0", FA0 },
		{ "fa1", FA1 },
		{ "fa2", FA2 },
		{ "fa3", FA3 },
		{ "fa4", FA4 },
		{ "fa5", FA5 },
		{ "fa6", FA6 },
		{ "fa7", FA7 },
		{ "fs2", FS2 },
		{ "fs3", FS3 },
		{ "fs4", FS4 },
		{ "fs5", FS5 },
		{ "fs6", FS6 },
		{ "fs7", FS7 },
		{ "fs8", FS8 },
		{ "fs9", FS9 },
		{ "fs10", FS10 },
		{ "fs11", FS11 },
		{ "ft8", FT8 },
		{ "ft9", FT9 },
		{ "ft10", FT10 },
		{ "ft1", FT11 },
		{ "callprintf", CALLPRINTF },
		{ "callscanf", CALLSCANF },
		{ "callcfunc", CALLCFUNC },
		{ "callstrlen", CALLSTRLEN }
	};
	token_hashmap = init_hashmap(pairs, sizeof(pairs) / sizeof(kvpair_t)); 
}

